blank_issues_enabled: false
contact_links:
  - name: 🌐 Resume Revise Official Website
    url: https://wangchujiang.com/ResumeRevise/
    about: Introduction to the Resume Revise app on the official website!